spring:
  application:
    name: smart

  csrf:
    enabled: true

#  datasource:
#    url: jdbc:mysql://127.0.0.1/smart?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: qwer1234

  datasource:
    url: jdbc:mariadb://svc.sel4.cloudtype.app:30759/smart?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: smart
    password: qwer1234

  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MariaDBDialect  # MySQLDialect에서 MariaDBDialect로 변경
    show-sql: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    # Jackson Timezone Configuration
  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    hibernate:
      type:
        descriptor:
          sql:
            BasicBinder: TRACE